[
  { type: "command", topic: "ssh", q: "Connect to a remote server at 192.168.1.100 using SSH with username 'user'.", answer: ["ssh user@192.168.1.100"], expl: "Basic SSH connection syntax is ssh username@hostname or IP address" },
  { type: "mc", topic: "ssh", q: "What is the default SSH port?", choices: ["21", "22", "23", "80"], answer: 1, expl: "SSH listens on TCP port 22 by default; Telnet uses 23 (obsolete)" },
  { type: "command", topic: "ssh", q: "Connect to a server on non-default port 2222 using SSH.", answer: ["ssh -p 2222 user@host", "ssh user@host -p 2222"], expl: "Use -p flag followed by port number for non-default ports" },
  { type: "output", topic: "ssh", q: "What does this SSH connection output indicate?", code: "The authenticity of host '192.168.1.50' can't be established.\nED25519 key fingerprint is SHA256:AbCd1234...\nAre you sure you want to continue?", answer: ["First time connecting to this server; host key fingerprint verification"], expl: "This is normal on first connection; the host key is saved to ~/.ssh/known_hosts" },
  { type: "command", topic: "ssh", q: "Run a single command remotely via SSH without opening an interactive shell.", answer: ["ssh user@host 'command'", "ssh user@host command"], expl: "Append the command at the end; no interactive session is created" },
  { type: "command", topic: "ssh", q: "Connect to a server with verbose output for debugging connection issues.", answer: ["ssh -v user@host"], expl: "Use -v for verbose mode; -vv and -vvv provide even more detail" },

  { type: "command", topic: "ssh-keys", q: "Generate a new Ed25519 SSH key pair for secure authentication.", answer: ["ssh-keygen -t ed25519 -C 'your_email@example.com'"], expl: "Ed25519 is modern, fast, and secure; provide a meaningful comment with -C" },
  { type: "mc", topic: "ssh-keys", q: "Where are private SSH keys typically stored?", choices: ["/etc/ssh", "~/.ssh/", "/usr/share/keys", "/var/ssh"], answer: 1, expl: "Private keys are in ~/.ssh/ with restricted permissions (600)" },
  { type: "command", topic: "ssh-keys", q: "Copy your public SSH key to a remote server to enable key-based authentication.", answer: ["ssh-copy-id user@192.168.1.50", "ssh-copy-id -i ~/.ssh/id_ed25519.pub user@host"], expl: "ssh-copy-id installs your public key in ~/.ssh/authorized_keys on the remote server" },
  { type: "mc", topic: "ssh-keys", q: "What is the purpose of a passphrase when generating SSH keys?", choices: ["Encrypt the private key file", "Speed up connections", "Authenticate to DNS", "Compress the key"], answer: 0, expl: "Passphrase protects the private key; even if stolen, it cannot be used without the passphrase" },
  { type: "output", topic: "ssh-keys", q: "After running ssh-keygen, what files are created?", answer: ["Private key (e.g., ~/.ssh/id_ed25519) and public key (e.g., ~/.ssh/id_ed25519.pub)"], expl: "Private key is sensitive and stays local; public key is shared with servers" },

  { type: "command", topic: "scp-sftp", q: "Upload a local file to a remote server using secure copy.", answer: ["scp file.txt user@192.168.1.50:~/"], expl: "SCP syntax: scp local_file username@host:remote_path" },
  { type: "command", topic: "scp-sftp", q: "Download a file from a remote server to your local machine.", answer: ["scp user@192.168.1.50:~/file.txt ."], expl: "Reverse the source and destination; . means current directory" },
  { type: "command", topic: "scp-sftp", q: "Upload an entire directory recursively to a remote server using SCP.", answer: ["scp -r myfolder/ user@host:~/"], expl: "-r flag enables recursive copying of directories" },
  { type: "command", topic: "scp-sftp", q: "Use SCP on a non-standard SSH port (2222) to transfer a file.", answer: ["scp -P 2222 file.txt user@host:~/"], expl: "Note: SCP uses capital -P (unlike SSH which uses lowercase -p)" },
  { type: "mc", topic: "scp-sftp", q: "What is the primary advantage of SFTP over SCP?", choices: ["Faster transfer speeds", "Interactive file browser for navigation", "Lower bandwidth usage", "Better compression"], answer: 1, expl: "SFTP provides an interactive shell-like interface; SCP is one-shot transfers" },
  { type: "command", topic: "scp-sftp", q: "Start an interactive SFTP session to a remote server.", answer: ["sftp user@192.168.1.50"], expl: "SFTP opens a session where you can navigate, upload, download, and manage files" },

  { type: "command", topic: "file-searching", q: "Find all .txt files in the current directory and subdirectories.", answer: ["find . -name '*.txt'"], expl: ". means start from current directory; -name matches filename pattern" },
  { type: "command", topic: "file-searching", q: "Find files larger than 10 megabytes.", answer: ["find / -size +10M"], expl: "+10M finds files larger than 10MB; -10M finds smaller; 10M finds exactly 10MB" },
  { type: "mc", topic: "file-searching", q: "What is the key difference between 'find' and 'locate' commands?", choices: ["find is faster", "locate searches a database; find searches real-time", "locate requires root", "find only works on Linux"], answer: 1, expl: "locate uses a pre-built database (updatedb); find searches live filesystem" },
  { type: "command", topic: "file-searching", q: "Find files modified within the last 7 days.", answer: ["find /home -mtime -7"], expl: "-mtime -7 means modified within last 7 days; use +7 for older files" },
  { type: "command", topic: "file-searching", q: "Find all directories (not files) in current location.", answer: ["find . -type d"], expl: "-type d matches directories; -type f matches files" },
  { type: "command", topic: "file-searching", q: "Find files owned by a specific user 'alice'.", answer: ["find /home -user alice"], expl: "-user username finds files by owner" },
  { type: "output", topic: "file-searching", q: "What does this command do?", code: "find . -name '*.log' -delete", answer: ["Finds all .log files and deletes them"], expl: "Use -delete with extreme caution; test with -ls first to preview matches" },

  { type: "command", topic: "text-searching", q: "Search for the word 'error' in a log file.", answer: ["grep 'error' system.log"], expl: "grep searches file contents for pattern matches" },
  { type: "command", topic: "text-searching", q: "Search for 'warning' case-insensitively in a log file.", answer: ["grep -i 'warning' system.log"], expl: "-i flag makes grep case-insensitive" },
  { type: "mc", topic: "text-searching", q: "Which grep flag recursively searches all files in a directory?", choices: ["-a", "-r", "-x", "-v"], answer: 1, expl: "-r (recursive) searches all files in directory and subdirectories" },
  { type: "command", topic: "text-searching", q: "Show line numbers for all matches of 'TODO' in a Python script.", answer: ["grep -n 'TODO' script.py"], expl: "-n flag adds line numbers to output" },
  { type: "command", topic: "text-searching", q: "Find all lines that do NOT contain 'debug' in a file.", answer: ["grep -v 'debug' system.log"], expl: "-v (invert match) shows lines that don't match the pattern" },
  { type: "output", topic: "text-searching", q: "What does 'grep -c error system.log' output?", answer: ["Number of lines containing 'error'"], expl: "-c counts matching lines instead of displaying them" },

  { type: "command", topic: "archiving-compression", q: "Create a tar archive of a directory without compression.", answer: ["tar -cvf backup.tar myfolder/"], expl: "-c create, -v verbose, -f filename" },
  { type: "command", topic: "archiving-compression", q: "Create a gzip-compressed tar archive.", answer: ["tar -czvf backup.tar.gz myfolder/"], expl: "-z adds gzip compression; .tar.gz is the result" },
  { type: "mc", topic: "archiving-compression", q: "What does the 'x' flag in tar do?", choices: ["Create archive", "Extract archive", "Exclude files", "Execute archive"], answer: 1, expl: "tar -x extracts files from an archive" },
  { type: "command", topic: "archiving-compression", q: "Extract a compressed tar.gz archive to a specific directory.", answer: ["tar -xzvf backup.tar.gz -C /tmp/restore/"], expl: "-C changes directory before extracting; -x extracts, -z decompresses" },
  { type: "command", topic: "archiving-compression", q: "List the contents of a tar archive without extracting.", answer: ["tar -tvf backup.tar", "tar -tzf backup.tar.gz"], expl: "-t lists contents; -v shows details; -z for gzip" },
  { type: "command", topic: "archiving-compression", q: "Compress a file using gzip.", answer: ["gzip file.txt"], expl: "gzip replaces file.txt with file.txt.gz" },
  { type: "command", topic: "archiving-compression", q: "Keep the original file while compressing with gzip.", answer: ["gzip -k file.txt"], expl: "-k keeps the original; creates file.txt.gz" },
  { type: "flags", topic: "archiving-compression", q: "Explain key tar flags.", flags: [
    { flag: "-c", answer: ["Create a new archive"] },
    { flag: "-x", answer: ["Extract files from archive"] },
    { flag: "-t", answer: ["List archive contents"] },
    { flag: "-v", answer: ["Verbose — show files processed"] },
    { flag: "-z", answer: ["Compress/decompress with gzip"] },
    { flag: "-j", answer: ["Compress/decompress with bzip2"] }
  ], expl: "Commonly combined: -czf creates gzip archive verbosely" },

  { type: "command", topic: "ip-commands", q: "Show all network interfaces and their IP addresses.", answer: ["ip addr show", "ip a"], expl: "Modern replacement for ifconfig; shows Layer 3 addressing" },
  { type: "command", topic: "ip-commands", q: "Bring down (disable) a network interface eth0.", answer: ["ip link set eth0 down"], expl: "ip link manages Layer 2; 'up' brings it back online" },
  { type: "mc", topic: "ip-commands", q: "Which ip subcommand shows the routing table?", choices: ["ip addr", "ip link", "ip route", "ip neigh"], answer: 2, expl: "ip route displays and manages routing table entries" },
  { type: "command", topic: "ip-commands", q: "Assign a static IP 10.0.0.5/24 to interface eth0.", answer: ["ip addr add 10.0.0.5/24 dev eth0"], expl: "ip addr add assigns address; use del to remove" },
  { type: "command", topic: "ip-commands", q: "View the ARP (neighbor) cache.", answer: ["ip neigh show", "ip n"], expl: "ip neigh shows MAC address mappings for local neighbors" },
  { type: "output", topic: "ip-commands", q: "What does the MTU field in 'ip link show' represent?", answer: ["Maximum Transmission Unit — largest packet size the interface can send"], expl: "Default MTU is 1500 bytes; smaller values required for PPPoE or tunnels" },

  { type: "command", topic: "ping-traceroute", q: "Ping a host 5 times and stop.", answer: ["ping -c 5 8.8.8.8"], expl: "-c flag sets count; without it, ping continues indefinitely" },
  { type: "command", topic: "ping-traceroute", q: "Test MTU path discovery by sending a 1400-byte ping.", answer: ["ping -c 1 -s 1400 google.com"], expl: "-s sets payload size in bytes; useful for MTU troubleshooting" },
  { type: "mc", topic: "ping-traceroute", q: "What does TTL in a ping response indicate?", choices: ["Packet age in seconds", "Number of hops traversed", "Time To Live remaining"], answer: 2, expl: "TTL starts at 64 or 128 and decrements per hop; remaining TTL shows hops traveled" },
  { type: "command", topic: "ping-traceroute", q: "Show the network path to a destination using traceroute.", answer: ["traceroute google.com"], expl: "traceroute traces each hop from your computer to destination" },
  { type: "command", topic: "ping-traceroute", q: "Use TCP SYN probes for traceroute to bypass UDP-blocking firewalls.", answer: ["traceroute -T google.com"], expl: "-T uses TCP SYN; useful when UDP/ICMP are blocked" },
  { type: "mc", topic: "ping-traceroute", q: "In traceroute output, what do '* * *' represent?", choices: ["Unreachable hops", "Routers dropping TTL-expired probes", "Complete path to destination", "DNS lookup failures"], answer: 1, expl: "Asterisks mean router isn't responding to probe packets (firewall or configuration)" },

  { type: "command", topic: "dns", q: "Query DNS for the A record of a domain using dig.", answer: ["dig google.com"], expl: "dig queries DNS; defaults to A record (IPv4)" },
  { type: "command", topic: "dns", q: "Look up MX (Mail Exchange) records for a domain.", answer: ["dig google.com MX"], expl: "MX records specify mail servers for the domain" },
  { type: "command", topic: "dns", q: "Perform a reverse DNS lookup for IP 8.8.8.8.", answer: ["dig -x 8.8.8.8"], expl: "-x performs reverse lookup (IP to hostname) using PTR records" },
  { type: "mc", topic: "dns", q: "Which file contains static hostname-to-IP mappings consulted before DNS?", choices: ["/etc/resolv.conf", "/etc/hosts", "/etc/hostname", "/etc/dns"], answer: 1, expl: "/etc/hosts is checked first; /etc/resolv.conf specifies DNS servers" },
  { type: "command", topic: "dns", q: "Query a specific nameserver for a domain.", answer: ["dig @8.8.8.8 google.com"], expl: "@server overrides default nameserver; useful for testing DNS propagation" },
  { type: "output", topic: "dns", q: "What does 'dig +trace google.com' show?", answer: ["Full DNS resolution chain from root servers to authoritative nameservers"], expl: "+trace shows each delegation step in DNS hierarchy" },

  { type: "command", topic: "sockets", q: "List all TCP listening sockets with port numbers and process information.", answer: ["ss -tlnp", "sudo ss -tlnp"], expl: "-t TCP, -l listening, -n numeric, -p process; may need sudo for process names" },
  { type: "mc", topic: "sockets", q: "Which command queries kernel netlink directly for socket information?", choices: ["netstat", "ss", "lsof", "ps"], answer: 1, expl: "ss is faster than netstat because it queries kernel directly via netlink" },
  { type: "command", topic: "sockets", q: "Show only ESTABLISHED TCP connections.", answer: ["ss -tnp state established"], expl: "state filter shows active connections; other states: time-wait, syn-sent, listen" },
  { type: "output", topic: "sockets", q: "What does 'ss -s' display?", answer: ["Protocol summary statistics for TCP, UDP, and other protocols"], expl: "Shows socket counts and aggregate information per protocol" },
  { type: "command", topic: "sockets", q: "Find which process is listening on port 8080.", answer: ["ss -tlnp 'sport = :8080'", "lsof -i :8080"], expl: "Both commands identify the process owning a specific port" },

  { type: "command", topic: "packet-capture", q: "Capture all traffic on interface eth0 to a file.", answer: ["sudo tcpdump -i eth0 -w capture.pcap"], expl: "-i interface, -w write to file; requires root" },
  { type: "command", topic: "packet-capture", q: "Capture HTTP traffic and display as human-readable ASCII.", answer: ["tcpdump -i any -A port 80"], expl: "-A prints ASCII payload; -i any captures on all interfaces" },
  { type: "mc", topic: "packet-capture", q: "What does tcpdump -s 0 do?", choices: ["Stop after 0 packets", "Capture full packet payload", "Set snapshot length to 0", "Skip fragmented packets"], answer: 1, expl: "-s 0 captures unlimited bytes per packet (default is 68); allows full payload inspection" },
  { type: "command", topic: "packet-capture", q: "Capture only DNS traffic (port 53).", answer: ["tcpdump -i any port 53"], expl: "port filter selects packets on specific port" },
  { type: "flags", topic: "packet-capture", q: "Explain tcpdump flags.", flags: [
    { flag: "-i", answer: ["Specify interface to capture on"] },
    { flag: "-w", answer: ["Write captured packets to file"] },
    { flag: "-r", answer: ["Read from saved capture file"] },
    { flag: "-A", answer: ["Print ASCII output of payload"] },
    { flag: "-v", answer: ["Verbose — show more protocol details"] }
  ], expl: "Common BPF filters: host, port, net, proto" },

  { type: "command", topic: "firewall", q: "Discover active hosts on your network without port scanning.", answer: ["nmap -sn 192.168.1.0/24"], expl: "-sn is ping sweep; finds live hosts without checking open ports" },
  { type: "command", topic: "firewall", q: "Scan for open ports on a target host.", answer: ["nmap 192.168.1.1"], expl: "Default scan checks common ports; use -p- for all 65535 ports" },
  { type: "mc", topic: "firewall", q: "Which nmap scan type sends SYN packets but doesn't complete the TCP handshake?", choices: ["-sT (TCP Connect)", "-sS (SYN Scan)", "-sU (UDP)", "-sF (FIN Scan)"], answer: 1, expl: "-sS sends SYN, receives SYN-ACK (port open), then RST (stealthy)" },
  { type: "command", topic: "firewall", q: "Detect service versions running on open ports.", answer: ["nmap -sV 192.168.1.1"], expl: "-sV queries services to determine versions; helps find vulnerable software" },
  { type: "mc", topic: "firewall", q: "What does 'nmap -O' do?", choices: ["Optimize scan speed", "Fingerprint the target operating system", "Only scan open ports", "Output results to file"], answer: 1, expl: "-O attempts OS detection based on TCP/IP behavior" },
  { type: "command", topic: "firewall", q: "Allow HTTPS traffic and deny Telnet using ufw.", answer: ["ufw allow 443/tcp", "ufw deny 23"], expl: "ufw uses simple allow/deny syntax; specify protocol if needed" },
  { type: "output", topic: "firewall", q: "What does 'sudo iptables -P INPUT DROP' accomplish?", answer: ["Sets default policy to drop (reject) all incoming connections"], expl: "Uses iptables -P (policy) to set chain default action" },

  { type: "command", topic: "networking", q: "Display routing table with destination, gateway, and interface.", answer: ["ip route show", "route -n"], expl: "ip route is modern; route is legacy but portable" },
  { type: "mc", topic: "networking", q: "In 'ip link show' output, what does 'LOWER_UP' mean?", choices: ["Interface is active in software", "Physical cable is connected", "Interface has a lower MTU", "Device has lower priority"], answer: 1, expl: "UP=software active, LOWER_UP=hardware connected; both needed for traffic" },
  { type: "command", topic: "networking", q: "Configure colorized output for ip commands.", answer: ["ip -c addr", "ip -c link"], expl: "-c flag enables colored output for easier reading" },
  { type: "mc", topic: "networking", q: "What command shows the most recent login time of all users?", choices: ["last", "lastlog", "who", "users"], answer: 1, expl: "lastlog displays last login per user; last shows login history" },
  { type: "command", topic: "networking", q: "Check which DNS servers your system uses.", answer: ["cat /etc/resolv.conf"], expl: "resolv.conf lists nameservers; modern systems may use systemd-resolved" },
  { type: "output", topic: "networking", q: "What do ARP cache entries show?", answer: ["IP address to MAC address mappings for local devices"], expl: "Used for Layer 2 switching; populated dynamically during communication" }
]