[
  { type: "command", topic: "environment-variables", q: "Display the value of the USER environment variable.", answer: ["echo $USER"], expl: "$ prefix tells bash to expand the variable value, not print its name" },
  { type: "mc", topic: "environment-variables", q: "Are environment variable names case-sensitive?", choices: ["No, $home and $HOME are the same", "Yes, $HOME and $home are different variables", "Only uppercase is valid", "Only lowercase works in bash"], answer: 1, expl: "$HOME is correct; $home returns empty (undefined)" },
  { type: "command", topic: "environment-variables", q: "List all currently set environment variables.", answer: ["printenv", "env"], expl: "printenv and env both list variables; pipe to less for scrolling" },
  { type: "command", topic: "environment-variables", q: "Display just the HOME variable using printenv.", answer: ["printenv HOME"], expl: "printenv can filter to single variable without using $" },
  { type: "output", topic: "environment-variables", q: "What does this command show?", code: "$ echo $SHELL", answer: ["/bin/bash", "/bin/sh", "The path to the current shell interpreter"], expl: "SHELL variable contains path to the current shell executable" },

  { type: "command", topic: "variable-creation", q: "Create a variable called MY_NAME with value 'Alice'.", answer: ["MY_NAME=\"Alice\""], expl: "No spaces around =; name uses alphanumeric and underscore only" },
  { type: "mc", topic: "variable-creation", q: "What happens if you type: MY_NAME = \"Alice\" (with spaces)?", choices: ["Creates variable MY_NAME", "Bash tries to run MY_NAME as a command", "Throws a syntax error", "Creates three separate variables"], answer: 1, expl: "Spaces around = cause bash to interpret MY_NAME as a command to execute" },
  { type: "command", topic: "variable-creation", q: "Create a variable PROJECT_DIR set to /home/student/myapp.", answer: ["PROJECT_DIR=\"/home/student/myapp\""], expl: "String values with special characters should be in quotes" },
  { type: "output", topic: "variable-creation", q: "What is the output after these commands?", code: "MY_VAR=\"test\"\necho $MY_VAR", answer: ["test"], expl: "Variable is defined and then expanded with echo" },
  { type: "command", topic: "variable-creation", q: "Use a variable inside a command to create a directory.", answer: ["mkdir -p $BACKUP_DIR"], expl: "Variables expand inside commands; combine with -p to create parent dirs" },

  { type: "command", topic: "variable-export", q: "Create and export a variable GREETING with value 'Hello'.", answer: ["export GREETING=\"Hello\""], expl: "export makes variable visible to child processes and subshells" },
  { type: "mc", topic: "variable-export", q: "What is the difference between local and exported variables?", choices: ["Exported variables have longer names", "Local variables are only in current shell; exported are visible to child processes", "Exported variables must start with capital letter", "There is no difference"], answer: 1, expl: "Without export, variable only exists in current shell; export passes to children" },
  { type: "command", topic: "variable-export", q: "Test that a variable is not visible to a subshell (bash -c command).", answer: ["bash -c 'echo $MY_VAR'"], expl: "Subshell cannot see non-exported variables; returns empty" },
  { type: "output", topic: "variable-export", q: "What happens when you run bash -c 'echo $GREETING' after GREETING=\"Hello\" (without export)?", answer: ["Outputs empty line (or nothing)"], expl: "Subshell doesn't inherit non-exported variables from parent" },
  { type: "command", topic: "variable-export", q: "Remove a variable entirely from the current shell.", answer: ["unset MY_VAR"], expl: "unset deletes variable; it no longer exists in this shell" },

  { type: "command", topic: "path-management", q: "Display the current PATH with each directory on a separate line.", answer: ["echo $PATH | tr ':' '\\n'"], expl: "tr translates colons to newlines for readable display" },
  { type: "mc", topic: "path-management", q: "What does PATH control in Linux?", choices: ["The current directory you're in", "Directories the shell searches for executable commands", "The file permissions system", "The terminal color scheme"], answer: 1, expl: "$PATH is a colon-separated list of directories bash searches for commands" },
  { type: "command", topic: "path-management", q: "Find the full path of the 'ls' command using the which command.", answer: ["which ls"], expl: "which shows which executable file will run when you type a command" },
  { type: "output", topic: "path-management", q: "What does 'which cd' return?", answer: ["No output (cd is a shell builtin, not a file in PATH)"], expl: "which only finds executables in PATH; shell builtins return no output" },
  { type: "command", topic: "path-management", q: "Add /home/student/scripts directory to the front of PATH for this session.", answer: ["export PATH=\"/home/student/scripts:$PATH\""], expl: ":$PATH at end preserves existing directories; new dir gets checked first" },
  { type: "mc", topic: "path-management", q: "What is wrong with: export PATH=\"/home/student/scripts\"?", choices: ["Syntax is correct", "This REPLACES PATH entirely, breaking system commands", "You must use quotes", "It adds the directory correctly"], answer: 1, expl: "Without :$PATH at the end, all other directories (like /usr/bin) are lost" },

  { type: "command", topic: "bashrc-configuration", q: "Open the bashrc file in nano editor.", answer: ["nano ~/.bashrc"], expl: "~/.bashrc is in home directory; nano is beginner-friendly editor" },
  { type: "mc", topic: "bashrc-configuration", q: "When is ~/.bashrc read by bash?", choices: ["Every time bash starts", "Only on first login", "Once per session", "Never — it's ignored"], answer: 0, expl: "~/.bashrc runs every time you open an interactive shell" },
  { type: "command", topic: "bashrc-configuration", q: "Reload bashrc changes in the current terminal without closing it.", answer: ["source ~/.bashrc", ". ~/.bashrc"], expl: "source executes file in current shell; . is shorthand" },
  { type: "output", topic: "bashrc-configuration", q: "If you add 'export MY_VAR=test' to ~/.bashrc, when does it become available?", answer: ["In new terminals after saving; use 'source ~/.bashrc' in current terminal"], expl: "Changes in .bashrc only apply to new shells unless you source it" },
  { type: "command", topic: "bashrc-configuration", q: "Add a custom variable and PATH extension to ~/.bashrc permanently.", answer: ["nano ~/.bashrc, then add: export EDITOR=\"nano\"\nexport PATH=\"/home/student/scripts:$PATH\""], expl: "Edit file, add lines at bottom, save with Ctrl+O, exit with Ctrl+X" },

  { type: "mc", topic: "vim-editor", q: "What is modal editing in Vim?", choices: ["Using mouse to select text", "Switching between different modes for different tasks", "Edit mode only", "A recent Vim feature"], answer: 1, expl: "Vim has Normal, Insert, and Command modes; you switch between them" },
  { type: "command", topic: "vim-editor", q: "Enter insert mode in vim to start typing.", answer: ["i", "a", "o"], expl: "i inserts before cursor, a appends after, o opens new line" },
  { type: "output", topic: "vim-editor", q: "What does pressing Esc do in vim?", answer: ["Returns from Insert mode to Normal mode"], expl: "Esc is critical for exiting insert mode; students often get stuck without it" },
  { type: "mc", topic: "vim-editor", q: "How do you save and quit in vim?", choices: [":q", ":w", ":wq", ":q!"], answer: 2, expl: ":wq saves and quits; :q! quits without saving; :w saves only" },
  { type: "command", topic: "vim-editor", q: "Copy (yank) and paste a line in vim.", answer: ["yy", "p"], expl: "yy copies current line; p pastes after cursor" },
  { type: "command", topic: "vim-editor", q: "Search for the word 'error' within a vim file.", answer: ["/error"], expl: "/ opens search; press n for next, N for previous match" },
  { type: "output", topic: "vim-editor", q: "In vim, what does u do?", answer: ["Undo the last action"], expl: "u undoes; Ctrl+r redoes" },
  { type: "flags", topic: "vim-editor", q: "Explain vim navigation keys.", flags: [
    { flag: "h", answer: ["Move cursor left"] },
    { flag: "j", answer: ["Move cursor down"] },
    { flag: "k", answer: ["Move cursor up"] },
    { flag: "l", answer: ["Move cursor right"] }
  ], expl: "Arrow keys work but hjkl is traditional vim navigation" },

  { type: "mc", topic: "nano-editor", q: "What is the main advantage of nano compared to vim?", choices: ["Faster speed", "No learning curve — shortcuts shown on screen", "Better for programming", "Supports plugins"], answer: 1, expl: "Nano shows available commands at bottom; no modes to learn" },
  { type: "command", topic: "nano-editor", q: "Exit nano editor and save changes.", answer: ["Ctrl+O, Enter, Ctrl+X"], expl: "Ctrl+O opens save dialog, Enter confirms filename, Ctrl+X exits" },
  { type: "output", topic: "nano-editor", q: "What keys are shown at the bottom of nano?", answer: ["Common shortcuts like Ctrl+X (Exit), Ctrl+O (Save), Ctrl+W (Search)"], expl: "Nano always displays help text; you don't memorize commands" },
  { type: "command", topic: "nano-editor", q: "Search for text within a nano file.", answer: ["Ctrl+W"], expl: "Ctrl+W opens search prompt; enter text and press Enter" },
  { type: "command", topic: "nano-editor", q: "Cut the current line in nano.", answer: ["Ctrl+K"], expl: "Ctrl+K cuts; Ctrl+U pastes; these are standard nano shortcuts" },
  { type: "mc", topic: "nano-editor", q: "Is nano pre-installed on most Linux systems?", choices: ["No, you must install it", "Yes, it's widely available", "Only on Ubuntu", "Rare on modern systems"], answer: 1, expl: "Nano is standard on most distributions; safe 'survival skill' choice" },

  { type: "mc", topic: "neovim", q: "What is Neovim?", choices: ["A complete rewrite of vim with no compatibility", "Vim improved with modern features", "A GUI editor similar to VS Code", "An obsolete version of vim"], answer: 1, expl: "Neovim is vim-compatible with LSP, async plugins, and Lua config" },
  { type: "output", topic: "neovim", q: "What advantage does Neovim have over Vim regarding plugin architecture?", answer: ["Plugins run asynchronously — no editor lag"], expl: "Neovim's async architecture prevents plugins from freezing the editor" },
  { type: "mc", topic: "neovim", q: "Does all Vim configuration work in Neovim?", choices: ["No, Neovim requires complete reconfiguration", "Mostly yes, most Vim configs transfer directly", "Only vimscript works, not Lua", "Neovim rejects all Vim configs"], answer: 1, expl: "Neovim is vim-compatible; muscle memory transfers directly" },
  { type: "mc", topic: "neovim", q: "What language does Neovim use for configuration instead of VimScript?", choices: ["Python", "Lua", "Bash", "Ruby"], answer: 1, expl: "Neovim supports Lua config which is faster and more modern" },
  { type: "mc", topic: "neovim", q: "Does Neovim come pre-installed on most Linux systems?", choices: ["Yes, it's the default", "No, you must install it separately", "Only on Ubuntu", "It's required on all servers"], answer: 1, expl: "Neovim is not pre-installed; you must install it via package manager" },

  { type: "mc", topic: "helix", q: "What is Helix?", choices: ["Another name for vim", "A modern Rust-based terminal editor with zero-config setup", "A GUI-only text editor", "A deprecated vim fork"], answer: 1, expl: "Helix is written in Rust, requires zero configuration, works out of the box" },
  { type: "output", topic: "helix", q: "What feature does Helix have built-in that typically requires plugins in Vim/Neovim?", answer: ["LSP (Language Server Protocol) and Tree-sitter syntax highlighting"], expl: "Helix comes with modern features pre-enabled without config" },
  { type: "mc", topic: "helix", q: "What is Helix's selection-first editing model?", choices: ["Only one selection allowed at a time", "Select text THEN apply commands (opposite of vim)", "A graphics mode for visual selection", "Pre-selection of entire files"], answer: 1, expl: "Helix reverses vim workflow: select first, then apply action" },
  { type: "mc", topic: "helix", q: "Does Helix have a plugin system?", choices: ["Yes, extensive plugin ecosystem", "No plugin system yet", "Only for color schemes", "Plugins are built-in only"], answer: 1, expl: "Helix has no plugin system; it provides features out of the box instead" },
  { type: "mc", topic: "helix", q: "What is Helix's main disadvantage compared to Neovim?", choices: ["Slower performance", "No terminal support", "Smaller community and fewer customization options", "Requires paid license"], answer: 2, expl: "Helix is rising but smaller community means fewer tutorials and less customization" },

  { type: "mc", topic: "vs-code", q: "Can VS Code be used as a terminal editor on a remote SSH server?", choices: ["Yes, it replaces vim entirely", "No, VS Code is GUI-only; use Remote SSH extension", "Only for local editing", "Never on remote servers"], answer: 1, expl: "VS Code itself is GUI-only but Remote SSH extension allows editing remote files" },
  { type: "mc", topic: "vs-code", q: "How many extensions does VS Code have available?", choices: ["Hundreds", "Thousands", "30,000+", "No extensions available"], answer: 2, expl: "VS Code ecosystem includes 30000+ extensions for languages, themes, and tools" },
  { type: "output", topic: "vs-code", q: "What built-in feature does VS Code have that mimics Vim?", answer: ["VSCodeVim extension provides Vim keybindings"], expl: "Installing VSCodeVim extension lets you use familiar vim commands in VS Code" },
  { type: "mc", topic: "vs-code", q: "What is VS Code best suited for?", choices: ["Terminal-only SSH sessions", "Full projects on your local machine", "Remote server administration", "Minimal system requirements"], answer: 1, expl: "VS Code requires GUI; excellent for local development with IDE features" },

  { type: "mc", topic: "text-editors", q: "If you SSH into a server with no GUI, which editors are available?", choices: ["VS Code (remote option)", "Vim, Nano, or Neovim (if installed)", "All of the above", "None — must use local editing"], answer: 1, expl: "On SSH servers with no GUI, terminal editors (vim, nano, neovim) are your only option" },
  { type: "command", topic: "text-editors", q: "Open a file for editing using the default EDITOR variable.", answer: ["$EDITOR filename", "nano filename", "vim filename"], expl: "EDITOR variable can be referenced to use user's preferred editor" },
  { type: "mc", topic: "text-editors", q: "What editor should a beginner learn FIRST according to best practices?", choices: ["Vim", "Nano", "VS Code", "Helix"], answer: 1, expl: "Nano is easiest to learn; use it for quick edits and survival skills" },
  { type: "mc", topic: "text-editors", q: "What editor has the steepest learning curve?", choices: ["Nano", "VS Code", "Vim/Neovim", "Helix"], answer: 2, expl: "Vim modal editing and command syntax require practice; hardest to learn" },
  { type: "mc", topic: "text-editors", q: "Which statement is true about pre-installed editors?", choices: ["All editors come pre-installed", "Only Nano and Vim are pre-installed everywhere", "VS Code is pre-installed on all servers", "Helix is standard on all Linux systems"], answer: 1, expl: "Vim and Nano are nearly universal; Neovim, Helix, and VS Code require installation" },

  { type: "command", topic: "environment-variables", q: "Check which directories are in your PATH.", answer: ["echo $PATH"], expl: "Returns colon-separated list of directories bash searches for commands" },
  { type: "command", topic: "path-management", q: "Create a scripts directory and make it executable.", answer: ["mkdir -p /home/student/scripts", "chmod +x /home/student/scripts/myscript"], expl: "Scripts must be executable; use chmod +x to set execute permission" },
  { type: "output", topic: "environment-variables", q: "What does 'echo $HOME' show?", answer: ["/home/username (your home directory path)"], expl: "HOME variable stores the path to current user's home directory" },
  { type: "command", topic: "variable-export", q: "Create a session-specific variable MYAPP pointing to your app directory.", answer: ["export MYAPP=\"/home/student/myapp\""], expl: "export makes it available to child processes in this session" },
  { type: "mc", topic: "bashrc-configuration", q: "Where should permanent environment variable settings be stored?", choices: ["/etc/environment", "~/.bashrc", "/tmp/vars", "~/.bash_profile only"], answer: 1, expl: "~/.bashrc is read for every interactive shell; best place for user variables" }
]